"""Session Report Addon — Phase 2.

Scans the output directory at shutdown for the artefacts produced by
other addons and renders both an HTML and a Markdown report.

Uses **only** the Python standard library — zero extra dependencies.
"""

from __future__ import annotations

import glob
import json
import os
import textwrap
from datetime import datetime, timezone
from pathlib import Path
from string import Template
from typing import Any

from addons.base import AbstractAddon

# ── HTML template (stdlib string.Template) ───────────────────────────
_HTML_TEMPLATE = Template(
    """\
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>MitmRouter Session Report — $session_id</title>
<style>
  body { font-family: system-ui, sans-serif; max-width: 900px; margin: 2rem auto; padding: 0 1rem; color: #222; }
  h1 { border-bottom: 2px solid #ccc; padding-bottom: .3rem; }
  h2 { margin-top: 2rem; }
  table { border-collapse: collapse; width: 100%; }
  th, td { text-align: left; padding: .4rem .6rem; border-bottom: 1px solid #e0e0e0; }
  th { background: #f5f5f5; }
  .metric { font-variant-numeric: tabular-nums; }
  .badge { display: inline-block; padding: .15em .5em; border-radius: 4px; font-size: .85em; background: #e8f0fe; color: #174ea6; }
  footer { margin-top: 3rem; font-size: .85em; color: #888; }
</style>
</head>
<body>
<h1>MitmRouter Session Report</h1>
<p><strong>Session:</strong> <code>$session_id</code><br>
<strong>Generated:</strong> $generated_at_utc<br>
<strong>Profile:</strong> $profile</p>

<h2>Summary</h2>
<table>
<tr><th>Metric</th><th>Value</th></tr>
<tr><td>Total Flows</td><td class="metric">$total_flows</td></tr>
<tr><td>Unique Hosts</td><td class="metric">$unique_hosts</td></tr>
<tr><td>Endpoints Discovered</td><td class="metric">$endpoint_count</td></tr>
<tr><td>Certificates Captured</td><td class="metric">$cert_count</td></tr>
<tr><td>OpenAPI Paths</td><td class="metric">$openapi_path_count</td></tr>
</table>

<h2>Top 10 Hosts by Request Count</h2>
<table>
<thead><tr><th>#</th><th>Host</th><th>Requests</th></tr></thead>
<tbody>
$top_hosts_rows
</tbody>
</table>

$cert_section

$openapi_section

<footer>Generated by MitmRouter — Session Report Addon</footer>
</body>
</html>"""
)

# ── Markdown template ─────────────────────────────────────────────────
_MD_TEMPLATE = Template(
    """\
# MitmRouter Session Report

**Session:** `$session_id`  
**Generated:** $generated_at_utc  
**Profile:** $profile  

## Summary

| Metric                 | Value           |
|------------------------|----------------:|
| Total Flows            | $total_flows    |
| Unique Hosts           | $unique_hosts   |
| Endpoints Discovered   | $endpoint_count |
| Certificates Captured  | $cert_count     |
| OpenAPI Paths          | $openapi_path_count |

## Top 10 Hosts by Request Count

| # | Host | Requests |
|---|------|---------:|
$top_hosts_rows

$cert_section

$openapi_section

---
*Generated by MitmRouter — Session Report Addon*
"""
)


def _tbl_row_html(rank: int, host: str, count: int) -> str:
    return f"<tr><td>{rank}</td><td>{host}</td><td class=\"metric\">{count}</td></tr>"


def _tbl_row_md(rank: int, host: str, count: int) -> str:
    return f"| {rank} | {host} | {count} |"


def _cert_table_html(certs: list[dict[str, Any]]) -> str:
    if not certs:
        return "<h2>Certificate Inventory</h2><p><em>No certificates captured.</em></p>"
    rows = []
    for c in certs:
        cn = ", ".join(c.get("subject", {}).get("commonName", ["?"]))
        sans = ", ".join(c.get("san_dns_names", [])) or "—"
        rows.append(f"<tr><td>{cn}</td><td>{sans}</td></tr>")
    return (
        "<h2>Certificate Inventory</h2>\n<table>\n"
        "<thead><tr><th>Common Name</th><th>SANs</th></tr></thead>\n<tbody>\n"
        + "\n".join(rows)
        + "\n</tbody>\n</table>"
    )


def _cert_table_md(certs: list[dict[str, Any]]) -> str:
    if not certs:
        return "## Certificate Inventory\n\n*No certificates captured.*\n"
    rows = []
    for c in certs:
        cn = ", ".join(c.get("subject", {}).get("commonName", ["?"]))
        sans = ", ".join(c.get("san_dns_names", [])) or "—"
        rows.append(f"| {cn} | {sans} |")
    return (
        "## Certificate Inventory\n\n| Common Name | SANs |\n|-------------|------|\n"
        + "\n".join(rows)
        + "\n"
    )


def _openapi_section_html(paths: list[str]) -> str:
    if not paths:
        return "<h2>OpenAPI Paths</h2><p><em>No paths discovered.</em></p>"
    items = "".join(f"<li><code>{p}</code></li>" for p in sorted(set(paths)))
    return f"<h2>OpenAPI Paths</h2><ul>{items}</ul>"


def _openapi_section_md(paths: list[str]) -> str:
    if not paths:
        return "## OpenAPI Paths\n\n*No paths discovered.*\n"
    items = "".join(f"- `{p}`\n" for p in sorted(set(paths)))
    return f"## OpenAPI Paths\n\n{items}\n"


class SessionReportAddon(AbstractAddon):
    """Render session reports in HTML and Markdown after shutdown."""

    name = "session_report"
    description = "Generate HTML and Markdown session reports from addon artefacts."

    # ── AbstractAddon interface ──────────────────────────────────────
    @property
    def category(self) -> str:
        return "reporting"

    @classmethod
    def manifest(cls) -> dict[str, Any]:
        return {
            "name": cls.name,
            "description": cls.description,
            "category": "reporting",
            "version": "2.0.0",
            "outputs": ["report.html", "report.md"],
            "consumes": [
                "inventory_*.json",
                "certificates_*.json",
                "api_spec.yaml",
                "api_spec.json",
                "traffic.jsonl",
            ],
        }

    def configure(self, output_dir: str) -> None:
        self.output_dir: str = output_dir
        os.makedirs(self.output_dir, exist_ok=True)

    # ── Report generation ────────────────────────────────────────────
    def shutdown(self) -> None:
        """Scan output_dir, aggregate artefacts, and write reports."""
        artefacts = self._scan()
        html: str = self._render_html(artefacts)
        md: str = self._render_md(artefacts)

        with open(os.path.join(self.output_dir, "report.html"), "w", encoding="utf-8") as fh:
            fh.write(html)
        with open(os.path.join(self.output_dir, "report.md"), "w", encoding="utf-8") as fh:
            fh.write(md)

    def _scan(self) -> dict[str, Any]:
        """Collect artefacts from the output directory."""
        od = self.output_dir

        # Inventory (endpoints)
        endpoints: list[dict[str, Any]] = []
        for fp in sorted(glob.glob(os.path.join(od, "inventory_*.json"))):
            try:
                with open(fp, encoding="utf-8") as fh:
                    data = json.load(fh)
                if isinstance(data, list):
                    endpoints.extend(data)
                elif isinstance(data, dict):
                    endpoints.append(data)
            except (json.JSONDecodeError, OSError):
                continue

        # Certificates
        certs: list[dict[str, Any]] = []
        for fp in sorted(glob.glob(os.path.join(od, "certificates_*.json"))):
            try:
                with open(fp, encoding="utf-8") as fh:
                    certs.append(json.load(fh))
            except (json.JSONDecodeError, OSError):
                continue

        # OpenAPI paths
        openapi_paths: list[str] = []
        for suffix in ("api_spec.yaml", "api_spec.yml", "api_spec.json"):
            fp = os.path.join(od, suffix)
            if not os.path.isfile(fp):
                continue
            try:
                with open(fp, encoding="utf-8") as fh:
                    if suffix.endswith((".yaml", ".yml")):
                        import yaml as _yaml  # local import — already in requirements

                        spec = _yaml.safe_load(fh)
                    else:
                        spec = json.load(fh)
                for path_str in (spec.get("paths") or {}).keys():
                    openapi_paths.append(path_str)
            except Exception:
                continue

        # Traffic summary (top hosts)
        traffic_fp = os.path.join(od, "traffic.jsonl")
        host_counts: dict[str, int] = {}
        total_flows = 0
        if os.path.isfile(traffic_fp):
            try:
                with open(traffic_fp, encoding="utf-8") as fh:
                    for line in fh:
                        line = line.strip()
                        if not line:
                            continue
                        try:
                            entry = json.loads(line)
                        except json.JSONDecodeError:
                            continue
                        total_flows += 1
                        host = entry.get("host") or entry.get("request", {}).get("host", "unknown")
                        host_counts[host] = host_counts.get(host, 0) + 1
            except OSError:
                pass

        unique_hosts = len(host_counts)
        top_hosts = sorted(host_counts.items(), key=lambda x: x[1], reverse=True)[:10]

        return {
            "session_id": datetime.now(timezone.utc).strftime("%Y%m%d-%H%M%S"),
            "generated_at_utc": datetime.now(timezone.utc).isoformat(),
            "profile": os.environ.get("MITMROUTER_PROFILE", "default"),
            "total_flows": total_flows,
            "unique_hosts": unique_hosts,
            "endpoint_count": len(endpoints),
            "cert_count": len(certs),
            "openapi_path_count": len(set(openapi_paths)),
            "top_hosts": top_hosts,
            "certs": certs,
            "openapi_paths": openapi_paths,
        }

    # ── Renderers ────────────────────────────────────────────────────
    def _render_html(self, data: dict[str, Any]) -> str:
        top_rows = "\n".join(
            _tbl_row_html(i, host, cnt) for i, (host, cnt) in enumerate(data["top_hosts"], 1)
        )
        return _HTML_TEMPLATE.substitute(
            session_id=data["session_id"],
            generated_at_utc=data["generated_at_utc"],
            profile=data["profile"],
            total_flows=data["total_flows"],
            unique_hosts=data["unique_hosts"],
            endpoint_count=data["endpoint_count"],
            cert_count=data["cert_count"],
            openapi_path_count=data["openapi_path_count"],
            top_hosts_rows=top_rows or "<tr><td colspan=\"3\"><em>No traffic data</em></td></tr>",
            cert_section=_cert_table_html(data["certs"]),
            openapi_section=_openapi_section_html(data["openapi_paths"]),
        )

    def _render_md(self, data: dict[str, Any]) -> str:
        top_rows = "\n".join(
            _tbl_row_md(i, host, cnt) for i, (host, cnt) in enumerate(data["top_hosts"], 1)
        )
        return _MD_TEMPLATE.substitute(
            session_id=data["session_id"],
            generated_at_utc=data["generated_at_utc"],
            profile=data["profile"],
            total_flows=data["total_flows"],
            unique_hosts=data["unique_hosts"],
            endpoint_count=data["endpoint_count"],
            cert_count=data["cert_count"],
            openapi_path_count=data["openapi_path_count"],
            top_hosts_rows=top_rows or "| — | *No traffic data* | — |",
            cert_section=_cert_table_md(data["certs"]),
            openapi_section=_openapi_section_md(data["openapi_paths"]),
        )