"""API Spec Extractor – generate OpenAPI 3.0 specs from captured HTTP traffic."""

from __future__ import annotations

import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from mitmproxy import ctx, http

from addons.core.addon_base import AbstractAddon

__addon_manifest__ = {
    "name": "api_spec_extractor",
    "class_name": "APISpecExtractor",
    "version": "1.0.0",
    "author": "mitmrouter-core",
    "description": "Generate OpenAPI 3.0/Swagger specifications from captured HTTP traffic",
    "dependencies": {"python": [], "system": []},
    "mitmproxy_api_version": ">=9.0.0",
    "supported_modes": ["ethernet", "wifi_ap", "hybrid"],
    "config_schema": {
        "output_file": {"type": "string", "required": True},
        "include_examples": {"type": "boolean", "default": False},
    },
    "events": ["response"],
    "health_check": True,
    "test_footprint": "light",
    "ci_bundled": True,
    "external_tool_integration": None,
}


class APISpecExtractor(AbstractAddon):
    """Build an OpenAPI 3.0 specification incrementally from live traffic."""

    def __init__(self) -> None:
        self._spec: dict[str, Any] = {
            "openapi": "3.0.0",
            "info": {
                "title": "Captured API Specification",
                "version": "0.0.0",
                "description": "Auto-generated by mitmrouter api_spec_extractor",
            },
            "servers": [],
            "paths": {},
        }
        self._servers: set[str] = set()
        self._output_file: Path | None = None
        self._include_examples: bool = False

    # ------------------------------------------------------------------ #
    # Lifecycle                                                           #
    # ------------------------------------------------------------------ #

    def load(self, loader: Any) -> None:  # noqa: ANN401
        loader.add_option(
            name="openapi_output_file",
            typespec=str,
            default="/tmp/mitmrouter/api_spec.yaml",
            help="Output file path for generated OpenAPI spec",
        )
        loader.add_option(
            name="openapi_include_examples",
            typespec=bool,
            default=False,
            help="Embed request/response examples in the spec",
        )
        loader.add_command("spec_export", self.cmd_export, "Export current OpenAPI spec")

    def configure(self, updated: set[str]) -> None:
        if "openapi_output_file" in updated:
            self._output_file = Path(ctx.options.openapi_output_file)
            self._output_file.parent.mkdir(parents=True, exist_ok=True)
        if "openapi_include_examples" in updated:
            self._include_examples = ctx.options.openapi_include_examples

    # ------------------------------------------------------------------ #
    # Event hooks                                                         #
    # ------------------------------------------------------------------ #

    def response(self, flow: http.HTTPFlow) -> None:
        if flow.request.scheme not in ("http", "https"):
            return

        server_url = f"{flow.request.scheme}://{flow.request.host}"
        if server_url not in self._servers:
            self._servers.add(server_url)
            self._spec["servers"] = [{"url": s} for s in sorted(self._servers)]

        path = flow.request.path or "/"
        method = flow.request.method.lower()

        if path not in self._spec["paths"]:
            self._spec["paths"][path] = {}

        operation: dict[str, Any] = {
            "summary": f"{method.upper()} {path}",
            "operationId": self._operation_id(method, path),
            "responses": {},
        }

        # Request body
        if flow.request.content and "json" in flow.request.headers.get("content-type", ""):
            try:
                schema = self._infer_schema(json.loads(flow.request.text))
                operation["requestBody"] = {
                    "content": {"application/json": {"schema": schema}}
                }
            except Exception:  # noqa: BLE001
                pass

        # Response
        status = str(flow.response.status_code)
        resp_entry: dict[str, Any] = {"description": f"HTTP {status}"}

        if flow.response.content and "json" in flow.response.headers.get("content-type", ""):
            try:
                schema = self._infer_schema(json.loads(flow.response.text))
                resp_entry["content"] = {"application/json": {"schema": schema}}
                if self._include_examples:
                    resp_entry["content"]["application/json"]["example"] = json.loads(
                        flow.response.text
                    )
            except Exception:  # noqa: BLE001
                pass

        operation["responses"][status] = resp_entry
        self._spec["paths"][path][method] = operation

    def shutdown(self) -> None:
        self._write_spec()

    # ------------------------------------------------------------------ #
    # Helpers                                                             #
    # ------------------------------------------------------------------ #

    @staticmethod
    def _operation_id(method: str, path: str) -> str:
        slug = path.replace("/", "_").replace("{", "").replace("}", "").strip("_")
        return f"{method}_{slug}" if slug else method

    def _infer_schema(self, obj: Any) -> dict[str, Any]:  # noqa: ANN401
        if isinstance(obj, dict):
            return {
                "type": "object",
                "properties": {k: self._infer_schema(v) for k, v in obj.items()},
            }
        if isinstance(obj, list):
            return {
                "type": "array",
                "items": self._infer_schema(obj[0]) if obj else {"type": "object"},
            }
        if isinstance(obj, bool):
            return {"type": "boolean"}
        if isinstance(obj, int):
            return {"type": "integer"}
        if isinstance(obj, float):
            return {"type": "number"}
        return {"type": "string"}

    def _write_spec(self) -> None:
        if self._output_file is None:
            return
        self._spec["info"]["version"] = datetime.now(tz=timezone.utc).strftime("%Y.%m.%d")

        try:
            import yaml  # optional dep

            with self._output_file.open("w", encoding="utf-8") as f:
                yaml.dump(self._spec, f, default_flow_style=False, allow_unicode=True)
        except ImportError:
            fallback = self._output_file.with_suffix(".json")
            fallback.write_text(json.dumps(self._spec, indent=2), encoding="utf-8")
            ctx.log.warn("[api_spec_extractor] pyyaml not installed; wrote JSON instead")
            return

        ctx.log.info(f"[api_spec_extractor] exported OpenAPI spec to {self._output_file}")

    def cmd_export(self) -> str:
        self._write_spec()
        return f"OpenAPI spec written to {self._output_file}"

    def health_check(self) -> dict[str, Any]:  # noqa: ANN401
        return {"status": "healthy", "paths": len(self._spec["paths"])}


addons = [APISpecExtractor()]
